### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by PizzaGuru** [beans-squared/MechanicCraft#17]
Hi! i just started playing this pack and i am having trouble passing the second quest for some reason when i build a stencil table it wont register in the quests that i actually did

**Comment by beans-squared** [comment]
Hello and thank you @PizzaGuru - working on a fix at the moment. Should be out in the next half hour.

For the time being, if you have cheats enabled, type the command `/ftbquests editing_mode`, then open the quests GUI, right-click the quest and select 'complete instantly'. You might have to do this for the part builder quest as well.
