### ISSUE TITLE
Mining Drill quest ought to depend on Refinery quest

### ISSUE THREAD

**Issue by codewarrior0** [beans-squared/MechanicCraft#2]
I was so excited to get a Mining Drill after spending only 10 research packs, only to find out I need to spend another 350 to learn how to make fuel for it!

Edit: The Mining Drill will use IE Biodiesel, ImmersivePetroleum Diesel, or Magneticraft Fuel.

**Comment by beans-squared** [comment]
Yes, this is true. Currently this pack is in its very early stages, and research costs will likely be very unbalanced until I get a sense of how to properly price things. The next update will be focused on balancing research costs and clarifying relationships with other research lines (ie, specifying that the Mining Drill depends on the Biodiesel/Diesel production line).

Thanks for playing my pack and for your patience as I make it less bad :)
