### ISSUE TITLE
Quest Rewards

### ISSUE THREAD

**Issue by Sir420Yoshii** [beans-squared/MechanicCraft#24]
The quest book is not giving the rewards for completing said quests. Also the quest for making Brick did not recognize the craft.

**Comment by beans-squared** [comment]
Thanks for the feedback!

When you complete a quest, the item in the "rewards" section is the thing that you unlock to be able to craft, you don't  recieve that item upon completion. Think of it as completing a research: completing that quest unlocks the technology of being able craft that item. I will work on a system to clarify this mechanic.

As for the Seared Bricks quest, that is in fact bugged. I will work on a fix for that. For now, if you have cheats enabled in your world, you can type in the command '/ftbquests editing_mode' and then right-click the quest, and select 'Complete Instantly'. This will allow you to bypass the quest requirements.
