### ISSUE TITLE
Cannot load to menu

### ISSUE THREAD

**Issue by Spyrox17** [beans-squared/MechanicCraft#37]
**Describe the bug**
This is my first time playing the modpack. I've downloaded it off of curse. The current version is 0.14.1.
Upon pressing play, the pack seems to load through the initial forge loading phase, but then crashes in the middle of it, preventing gameplay completely. I've tried running with the minimum and recommended ram usage and around 10GB. I've had the same issue with or without optifine and even after reinstalling the whole pack.

**To Reproduce**
1. Start the pack new,
2. Try to play the pack.

**Expected behavior**
I expect the pack to not crash on startup and allow me to play the game as expected.

**Reports (please complete the following information using a website like [pastebin](https://pastebin.com/)):**
latest.log - https://pastebin.com/7CHGKM3H

**Comment by beans-squared** [comment]
@Spyrox17 Try disabling FoamFix in the modlist before starting the pack up again.

**Comment by Spyrox17** [comment]
Yep that fixed it.
